# Generated by Django 3.1.6 on 2021-03-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210305_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlist',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
