# Generated by Django 3.1.6 on 2021-03-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210305_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlist',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='budgetlist',
            name='savings_goal',
            field=models.FloatField(default=0.0),
        ),
    ]
