# Generated by Django 3.1.6 on 2021-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210306_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlist',
            name='paymentOrIncome',
        ),
        migrations.AlterField(
            model_name='paymentlist',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
