# Generated by Django 3.1.6 on 2021-03-08 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20210308_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentList',
            new_name='Payments',
        ),
    ]
