# Generated by Django 3.1.6 on 2021-03-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_payments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
    ]
