# Generated by Django 3.1.6 on 2021-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paymentOrIncome',
            field=models.BooleanField(null=True),
        ),
    ]
