# Generated by Django 3.1.6 on 2021-03-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210308_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paymentOrIncome',
            new_name='type',
        ),
    ]
