# Generated by Django 3.1.6 on 2021-03-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210306_1743'),
        ('dashboard', '0022_auto_20210308_2144'),
    ]

    operations = [
    ]
