# Generated by Django 3.1.6 on 2021-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_merge_20210309_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='is_cash_in_flow',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='is_cash_out_flow',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='name',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Income', 'Income')], default='payment', max_length=26, null=True),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
