# Generated by Django 3.1.6 on 2021-03-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210309_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='CashFlow',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='budget_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.budgetlist'),
        ),
    ]
