# Generated by Django 3.1.6 on 2021-03-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20210309_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='budget_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.budgetlist'),
        ),
    ]
