# Generated by Django 3.1.6 on 2021-03-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210309_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='budget_list',
            new_name='user',
        ),
    ]
