# Generated by Django 3.1.6 on 2021-03-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0034_auto_20210309_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='budget_list',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflow', to=settings.AUTH_USER_MODEL),
        ),
    ]
