# Generated by Django 3.1.6 on 2021-03-16 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20210315_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.AlterField(
            model_name='settings',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='settings',
            name='student_status',
            field=models.BooleanField(blank=True),
        ),
    ]
