# Generated by Django 3.1.6 on 2021-03-15 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_cashflow_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='date',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='day',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='month',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='recurring',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
