# Generated by Django 3.1.6 on 2021-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20210315_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='icon',
        ),
        migrations.AddField(
            model_name='settings',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
