# Generated by Django 3.1.6 on 2021-03-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20210315_1812'),
        ('dashboard', '0043_auto_20210316_0106'),
    ]

    operations = [
    ]
