# Generated by Django 3.1.6 on 2021-03-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20210316_1644'),
        ('dashboard', '0045_auto_20210316_1822'),
    ]

    operations = [
    ]
