# Generated by Django 3.1.6 on 2021-03-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_merge_20210317_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='recurring',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
