# Generated by Django 3.1.6 on 2021-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_cashflow_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='recurring',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
