# Generated by Django 3.1.6 on 2021-03-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_merge_20210317_1703'),
        ('dashboard', '0048_auto_20210319_1659'),
    ]

    operations = [
    ]
